'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import TheFooter from "@/components/TheFooter";
import TheHeader from "@/components/TheHeader";
import {Provider} from "react-redux";
import {store} from "@/redux/store";


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
  <Provider store={store}>
    <html lang="en">
      <body className={inter.className}>
      <TheHeader/>
      {children}
      <TheFooter/>
      </body>
    </html>
  </Provider>
  )
}
